# -*- coding: utf-8 -*-
"""Tugas Pt 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LNk-EvcXTf_jqeO_yvgAHp6uqaieazGS
"""

pip install numpy

import numpy as np

# Membuat matriks 5x5 dengan angka 11 hingga 35
angka = np.arange(11, 36)
matriks = angka.reshape(5, 5)

# Fungsi untuk memberi warna pada angka-angka tertentu
def warna_angka(angka):
    if angka in [11, 13, 15, 21, 23, 25, 31, 33, 35]:
        return "\033[32m{}\033[0m".format(angka) # Hijau
    elif angka in [12, 14]:
        return "\033[31m{}\033[0m".format(angka) # Merah
    elif angka in [16, 26]:
        return "\033[34m{}\033[0m".format(angka) # Biru
    elif angka in [12, 17, 22, 27, 32]:
        return "\033[91m{}\033[0m".format(angka) # Merah Muda
    else:
        return str(angka)

# Mengubah setiap elemen matriks dengan fungsi warna_angka
matriks_warna = np.vectorize(warna_angka)(matriks)

# Menampilkan matriks dengan warna pada angka-angka tertentu
for baris in matriks_warna:
    print(" ".join(baris))